from pathlib import Path
from html import escape as e
import json,os
from content import PROFILE as P, CASES, EXPERIENCE

root=Path(os.environ.get('MARKETING_OUTPUT_DIR',Path(__file__).parent.parent/'outputs'/'marketing'))
site=root/'website'
site.mkdir(parents=True,exist_ok=True)
def write(path,content):
 p=site/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content,encoding='utf-8')

def nav(active=''):
 return '''<a class="skip" href="#main">Skip to content</a><header class="header"><a class="wordmark" href="/" aria-label="KAThu on marketing home">KAThu<span>on marketing</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="navigation">Menu</button><nav id="navigation" aria-label="Main navigation"><a href="/#work">Work</a><a href="/#approach">Approach</a><a href="/#about">About</a><a href="/#experience">Experience</a><a class="nav-contact" href="/#contact">Let’s talk</a></nav></header>'''

def footer():
 return f'''<footer class="footer"><a class="wordmark" href="/">KAThu<span>on marketing</span></a><p>Phan Hoai Thu · Ho Chi Minh City</p><div><a href="{P['linkedin']}">LinkedIn</a><a href="https://kathuatwork.com/">Data portfolio</a><a href="mailto:{P['email']}">Email</a></div><small>© 2026 Phan Hoai Thu</small></footer>'''

def page(title,desc,body,path='/'):
 return f'''<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#5936c9"><title>{e(title)} | KAThu on marketing</title><meta name="description" content="{e(desc,quote=True)}"><link rel="canonical" href="{P['site']}{path}"><meta property="og:title" content="{e(title,quote=True)}"><meta property="og:description" content="{e(desc,quote=True)}"><meta property="og:type" content="website"><meta property="og:url" content="{P['site']}{path}"><meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body>{nav()}<main id="main">{body}</main>{footer()}</body></html>'''

def card(c,feature=False):
 img=f'<img src="/assets/{c["images"][0][0]}" alt="{e(c["images"][0][1])}" loading="lazy" width="1000" height="562">' if c['images'] else '<div class="text-art"><span>Acquisition</span><span>Activation</span><span>Retention</span><span>Value</span></div>'
 return f'''<article class="work-card {'featured-card' if feature else ''}" data-category="{e(c['category'])}"><a class="card-image" href="/work/{c['slug']}/" tabindex="-1" aria-hidden="true">{img}</a><div class="card-body"><div class="card-meta"><span>{e(c['client'])}</span><span>{e(c['kind'])}</span></div><h3><a href="/work/{c['slug']}/">{e(c['title'])}</a></h3><p>{e(c['intro'])}</p><div class="card-result"><strong>{e(c['metric'])}</strong><span>{e(c['metric_label'])}</span></div><a class="text-link" href="/work/{c['slug']}/">Read case study<span class="sr-only">: {e(c['client'])}</span></a></div></article>'''

featured=''.join(card(CASES[i],True) for i in [0,1,3])
library=''.join(card(c) for c in CASES)
categories=['All work']+list(dict.fromkeys(c['category'] for c in CASES))
filters=''.join(f'<button type="button" class="filter {"active" if i==0 else ""}" aria-pressed="{"true" if i==0 else "false"}" data-filter="{e(v)}">{e(v)}</button>' for i,v in enumerate(categories))
exp=''.join(f'<article class="experience-row"><p class="date">{x["dates"]}</p><div><h3>{x["company"]}</h3><p class="role">{x["role"]}</p><p>{e(x["bullets"][0])}</p></div></article>' for x in EXPERIENCE)
home=f'''
<section class="hero wrap"><div class="hero-copy"><p class="intro-label">Phan Hoai Thu (Katherine)</p><h1>A marketer who follows the whole journey.</h1><p class="hero-lede">I build campaigns, grow search visibility and improve the path to conversion. Data helps me understand what people need—and where to go next.</p><div class="hero-actions"><a class="button primary" href="#work">Explore my work</a><a class="button secondary" href="/documents/Phan_Hoai_Thu_Digital_Marketing_CV.pdf" download>Download CV</a></div><p class="hero-location">Digital marketing & growth · Ho Chi Minh City</p></div><div class="hero-visual"><div class="portrait-frame"><img src="/assets/katherine-ava.png" alt="Phan Hoai Thu" fetchpriority="high" width="850" height="1100"></div><div class="hero-note"><span>My starting point</span><p>What will move<br>the customer forward?</p></div></div></section>
<div class="brand-band"><div class="wrap"><p>Marketing across different customer journeys</p><div><span>B2B technology</span><span>Education</span><span>SaaS</span><span>E-commerce</span></div></div></div>
<section class="section wrap" aria-labelledby="selected-heading"><div class="section-heading"><div><p class="section-kicker">Selected campaign work</p><h2 id="selected-heading">The strategy.<br>The work. The results.</h2></div><p>From choosing a channel to improving the next click, these projects show how I connect execution with measurement.</p></div><div class="featured-grid">{featured}</div></section>
<section class="approach section" id="approach"><div class="wrap approach-grid"><div><p class="section-kicker">How I work</p><h2>Start with a customer.<br>Make a clear decision.</h2><p>A strong campaign brings audience understanding, creative execution and useful measurement into the same conversation.</p></div><div class="approach-steps"><article><span>01</span><div><h3>Understand the audience</h3><p>Research the market, search intent and customer journey. Decide which problem the campaign should solve.</p></div></article><article><span>02</span><div><h3>Build the path</h3><p>Connect the message, channel, content and landing page. Work closely with creative, product and sales.</p></div></article><article><span>03</span><div><h3>Measure, learn, improve</h3><p>Check tracking, review conversion and lead quality, and turn the next question into a useful test.</p></div></article></div></div></section>
<section class="section wrap" id="work"><div class="section-heading"><div><p class="section-kicker">The complete portfolio</p><h2>Campaigns and the thinking behind them.</h2></div><p>Professional work comes first. Independent projects extend the story into retention, promotions, targeting and experimentation.</p></div><div class="filters" role="group" aria-label="Filter case studies">{filters}</div><p class="result-count" aria-live="polite">13 case studies</p><div class="work-grid">{library}</div></section>
<section class="about section" id="about"><div class="wrap about-grid"><div><p class="section-kicker">A little about me</p><h2>Marketing is my craft.<br>Analysis sharpens it.</h2><p>I’m Thu, also known as Katherine. My experience spans paid campaigns, organic growth and customer journeys across international technology brands and e-commerce.</p><p>I enjoy the full process: understanding a market, shaping a plan with the team, getting the work live and asking whether it changed the right behavior.</p><p>SQL, dashboards and experiments give me a deeper view of that last question. The work still starts with a marketing decision.</p><a class="text-link" href="{P['linkedin']}">Meet me on LinkedIn</a></div><div class="capabilities"><h3>What I bring</h3><dl><dt>Acquire</dt><dd>Google Ads, Meta Ads, SEO, keyword and audience research, content planning</dd><dt>Convert</dt><dd>Landing-page strategy, customer journeys, CRO, creative testing, CRM lead insight</dd><dt>Understand</dt><dd>GA4, GTM, Looker Studio, Excel, SQL, Power BI, customer segmentation</dd><dt>Deliver</dt><dd>Cross-functional coordination, team coaching, reporting, CMS and workflow planning</dd></dl><div class="education"><strong>Bachelor of Business Administration</strong><span>University of Economics Ho Chi Minh City · 2018–2022</span><span>TheHau Data Analytics Mentoring Program · 2025</span><span>IELTS overall 7.5 · 2022</span></div></div></div></section>
<section class="section wrap" id="experience"><div class="section-heading"><div><p class="section-kicker">Experience</p><h2>Built through real work.</h2></div><a class="button secondary" href="/documents/Phan_Hoai_Thu_Digital_Marketing_CV.pdf" download>Download full CV</a></div>{exp}<article class="experience-row"><p class="date">2026</p><div><h3>Independent growth and analytics projects</h3><p>Experiment interpretation, campaign targeting, customer segmentation, promotion review and retention strategy. Each project is labeled with its evidence and limitations.</p></div></article></section>
<section class="contact" id="contact"><div class="wrap"><p class="section-kicker">Let’s talk</p><h2>Bring me a marketing<br>problem worth solving.</h2><a class="email-link" href="mailto:{P['email']}">{P['email']}</a><div class="contact-links"><a href="{P['linkedin']}">LinkedIn</a><a href="tel:+84817375930">+84 817 375 930</a><a href="/documents/Phan_Hoai_Thu_Digital_Marketing_CV.pdf" download>Download CV</a></div></div></section>'''
write('index.html',page('Phan Hoai Thu | Digital marketing & growth',P['summary'],home))

for c in CASES:
 actions=''.join(f'<li>{e(a)}</li>' for a in c['actions'])
 findings=''.join(f'<article><h3>{e(t)}</h3><p>{e(s)}</p></article>' for t,s in c['findings'])
 pics=''.join(f'<figure><a href="/assets/{name}" target="_blank" rel="noopener"><img src="/assets/{name}" alt="{e(cap)}" loading="lazy" width="1200" height="675"></a><figcaption>{e(cap)}. Open image for a closer view.</figcaption></figure>' for name,cap in c['images'])
 sources=''.join(f'<li><a href="{e(url,quote=True)}">{e(label)}</a></li>' if url.startswith('https://') else f'<li>{e(label)}: {e(url)}</li>' for label,url in c['sources'])
 related=[x for x in CASES if x['slug']!=c['slug'] and x['category']==c['category']][:2]
 if len(related)<2:related+=[x for x in CASES if x['slug']!=c['slug'] and x not in related][:2-len(related)]
 rel=''.join(f'<a href="/work/{x["slug"]}/"><span>{e(x["client"])}</span><h3>{e(x["title"])}</h3></a>' for x in related)
 body=f'''<section class="case-hero wrap"><a class="back-link" href="/#work">Back to all work</a><div class="case-labels"><span>{e(c['client'])}</span><span>{e(c['kind'])}</span><span>{e(c['category'])}</span></div><h1>{e(c['title'])}</h1><p class="case-intro">{e(c['intro'])}</p><div class="case-result"><strong>{e(c['metric'])}</strong><span>{e(c['metric_label'])}</span></div><div class="tool-list">{''.join(f'<span>{e(t)}</span>' for t in c['tools'])}</div></section><div class="case-layout wrap"><aside class="case-nav" aria-label="Case study sections"><a href="#challenge">The challenge</a><a href="#work-done">What I did</a><a href="#findings">What I learned</a><a href="#decision">Marketing decision</a><a href="#evidence">Project evidence</a><a href="#context">Context & sources</a></aside><div class="case-content"><section id="challenge"><h2>The challenge</h2><p>{e(c['challenge'])}</p></section><section id="work-done"><h2>What I did</h2><ul class="actions-list">{actions}</ul></section><section id="findings"><h2>What the work showed</h2><div class="finding-list">{findings}</div></section><section id="decision" class="decision"><p class="section-kicker">The marketing decision</p><h2>Where this leads</h2><p>{e(c['decision'])}</p></section><section id="evidence"><h2>Project evidence</h2>{pics if pics else '<p>This public summary preserves the approach and recommendations. Confidential business figures and source materials are kept out of this page.</p>'}</section><section id="context" class="source-context"><h2>Context and sources</h2><p>{e(c['limits'])}</p><ul>{sources}</ul></section></div></div><section class="section wrap"><h2>Continue exploring</h2><div class="related">{rel}</div></section>'''
 write(f'work/{c["slug"]}/index.html',page(c['title'],c['intro'],body,f'/work/{c["slug"]}/'))

write('404.html',page('Page not found','Find Phan Hoai Thu’s marketing portfolio.','<section class="section wrap"><h1>This page has moved.</h1><p>Explore the full portfolio to find the case study you need.</p><a class="button primary" href="/#work">Go to the portfolio</a></section>'))
write('robots.txt',f'User-agent: *\nAllow: /\nSitemap: {P["site"]}/sitemap.xml\n')
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{P["site"]}{x}</loc></url>' for x in ['/']+[f'/work/{c["slug"]}/' for c in CASES])+'</urlset>')
write('favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="16" fill="#5936c9"/><text x="32" y="45" text-anchor="middle" font-family="Arial,sans-serif" font-size="42" font-weight="700" fill="#ffd749">K</text></svg>')
write('vercel.json',json.dumps({'version':2,'cleanUrls':True,'trailingSlash':True,'headers':[{'source':'/(.*)','headers':[{'key':'X-Content-Type-Options','value':'nosniff'},{'key':'Referrer-Policy','value':'strict-origin-when-cross-origin'},{'key':'X-Frame-Options','value':'SAMEORIGIN'}]}]},indent=2))
write('.vercelignore','.git\n.vercel\nnode_modules\n')
write('package.json',json.dumps({'name':'kathuonmkt','private':True,'version':'1.0.0','description':'Phan Hoai Thu marketing portfolio','scripts':{'dev':'python -m http.server 4173','deploy':'vercel --prod'},'engines':{'node':'24.x'}},indent=2))
(root/'content.json').write_text(json.dumps({'profile':P,'experience':EXPERIENCE,'cases':CASES},ensure_ascii=False,indent=2),encoding='utf-8')
print('Built',len(CASES),'case studies and homepage')
