"""Verified public content for the Data/BI and Marketing Analyst tracks.

Evidence reviewed 18 September 2026. Employment dates confirmed by Thu.
TrueProfit omitted at Thu's request. No planned project is presented as completed.
"""
PROFILE = dict(name='Phan Hoai Thu', email='phanhoaithu114@gmail.com', phone='0817 375 930',
    location='Ho Chi Minh City, Vietnam', linkedin='https://www.linkedin.com/in/phanhoaithu114/',
    github='https://github.com/kath-pahotu', voice='I turn messy evidence into clear business decisions.')
TRACKS = {
 'data': dict(role='Data Analyst / BI Analyst', site='https://kathuatwork.com', cv='Phan_Hoai_Thu_DA_BI_CV',
   order=['thelook','rokt','bank','zalopay','mobility'], featured=['thelook','rokt','bank','zalopay'],
   summary='Data Analyst / BI Analyst with 3+ years across ecommerce, SaaS client work and digital marketing. Builds reproducible SQL/Python pipelines, trusted KPI models and clear BI reporting. Independent projects demonstrate propensity modeling, experiment analysis and rule-based review prioritization; professional work adds commercial context and project leadership.',
   lede='I connect reliable data models with the decisions they need to support: where revenue leaks, who to contact and whether a campaign worked.'),
 'marketing': dict(role='Marketing Analyst', site='https://kathuonmkt.vercel.app', cv='Phan_Hoai_Thu_Marketing_Analyst_CV',
   order=['mobility','bank','rokt','zalopay','thelook'], featured=['mobility','bank','rokt'],
   summary='Marketing Analyst with 3+ years across digital marketing, SaaS client work and ecommerce. Combines campaign leadership, channel measurement and conversion analysis with SQL, Python and BI. Uses targeting, funnel and retention analysis, promotion-cost review and experiment evaluation to turn evidence into practical growth decisions.',
   lede='I bring campaign experience and analytical depth to acquisition, promotion spend, conversion and retention. Every analysis starts with a marketing decision.')
}
EXPERIENCE = [
 dict(id='golden-owl', company='Golden Owl Solutions', role='Digital Marketing Analyst', dates='Apr 2024 - Sep 2025', domain='SaaS and technology agency',
   intro='Multi-client software agency work across SaaS, technology, ecommerce and retail. I led planning and delivery, translating management goals into project KPIs, milestones and team responsibilities.',
   data=[
    'Delivered 70+ analyses across 15 client businesses, connecting web, lead and campaign evidence to channel, funnel and customer-journey decisions.',
    'Built GA4 and Looker Studio reporting, clarified KPI definitions and investigated conversion drop-offs and lead-quality differences.',
    'Defined project KPIs, allocated resources, trained and guided contributors, and owned progress against agreed targets.'],
   marketing=[
    'Led campaign planning, KPI definition, resource allocation and team guidance across paid acquisition, SEO and conversion work.',
    'Used lead quality and geographic performance to guide Golden Owl campaign allocation; reported Work-with-us CPL fell from VND 1.6M to VND 736K.',
    'Built GA4 and Looker Studio reporting and delivered 70+ analyses across 15 client businesses to inform channel, content and funnel decisions.'],
   web=[('Acquisition and channel measurement','Planned Google Search, Performance Max and Meta activity, compared lead quality and geography, and connected budget pacing to campaign KPIs.'),
        ('Content and product intent','For SaaS clients including TurisVPN and LeaseRunner, connected SEO and content planning to download or signup paths. These events indicate intent; activation and revenue require separate measurement.'),
        ('Leadership and reporting','Defined smaller goals from management objectives, allocated work, coached contributors and reported progress. Professional dashboards used GA4 and Looker Studio.')]),
 dict(id='laptop-sgn', company='Laptop SGN', role='E-commerce Analyst (Freelance)', dates='Jul 2025 - Dec 2025', domain='Retail ecommerce and electronics',
   intro='A freelance analytics engagement alongside agency work, focused on acquisition, merchandising and repeat purchase for an electronics retailer.',
   data=[
    'Analyzed 100,000+ GA4, channel, product and transaction records with BigQuery, SQL and Excel to connect acquisition with commercial performance.',
    'Diagnosed product-to-cart conversion of 21.5% and compared new and returning customers to prioritize funnel and retention recommendations.'],
   marketing=[
    'Connected 100,000+ GA4, channel, product and transaction records to acquisition, merchandising and retention questions using BigQuery, SQL and Excel.',
    'Identified product-to-cart conversion of 21.5% as a funnel constraint and developed recommendations from channel, device and returning-customer behavior.'],
   web=[('Commercial decisions','Connected channel acquisition with product behavior, sales and customer segments. Recommendations focused on product decision support, cart progression and repeat use.'),
        ('Analytical ownership','Owned the question, KPI definitions, data preparation, analysis and recommendations. Findings were observational; subsequent revenue lift was not measured.')]),
 dict(id='canawan', company='Canawan Global', role='Digital Marketing Executive', dates='Sep 2022 - Apr 2024', domain='Etsy and Amazon ecommerce operations',
   intro='Hands-on marketplace and dropshipping operations, with product research, listing mechanics, content planning and acquisition reporting.',
   data=[
    'Worked across Etsy/Amazon marketplace and dropshipping operations; standardized product and category information across a 1,000+ SKU catalog.',
    'Connected acquisition, product and revenue reporting; led a three-person content team and automated WooCommerce workflows with n8n and Google Sheets.'],
   marketing=[
    'Led a three-person content team across ecommerce and affiliate work, setting content priorities, shared KPIs and reporting schedules.',
    'Combined Etsy/Amazon marketplace and dropshipping knowledge with product research and acquisition reporting across a 1,000+ SKU catalog.'],
   web=[('Marketplace knowledge','Product and listing decisions were grounded in ecommerce operations, catalog structure and customer demand across Etsy and Amazon.'),
        ('Team and workflow','Set content priorities and reporting schedules, trained contributors, and used n8n and Google Sheets to automate WooCommerce publishing.')])
]

CASES = {
 'thelook': dict(name='TheLook ecommerce', domain='Ecommerce', capability='Growth and retention',
   data_slug='thelook-ecommerce', marketing_slug='thelook', duration='Approximately 1 month',
   provenance='Independent project using synthetic retail data', tools=['DuckDB SQL','Python','Power BI','Star-schema modeling'],
   metric='$8.10M', metric_label='net sales reconciled in synthetic data', image='thelook-customer.png',
   data_title='A reproducible pipeline for the whole ecommerce journey',
   marketing_title='Find where acquisition stops becoming customer value',
   data_intro='From seven raw files and 2.42M events to validated sessions, a star schema and a seven-page Power BI report.',
   marketing_intro='Connect acquisition, checkout, repeat purchase and returns to decide where a lifecycle or conversion test belongs.',
   problem='Which parts of the customer journey deserve attention when acquisition, orders and customer behavior live in separate files?',
   methods=[('Reproducible ELT','Loaded seven original files into DuckDB, normalized fields in staging, rebuilt sessions from raw events and created conformed dimensions, facts and decision marts.'),
     ('Commercial KPI definitions','Separated gross demand from net sales by excluding cancelled and returned item value. Kept order, item, session and customer grains explicit.'),
     ('Funnel and customer analysis','Analyzed session conversion, cart abandonment, cohort retention and RFM segments. Kept session traffic source separate from customer acquisition source because their taxonomies differ.'),
     ('Validation and BI','Reconciled counts and KPI totals, enforced data contracts and modeled Power BI without fact-to-fact relationships. Excluded invalid shipment timestamps from delivery metrics.')],
   results=[('124,814','orders across Jan 2019-May 2024'),('680,862','sessions rebuilt from events'),('58.0%','cart abandonment in the sample'),('37.3%','repeat-customer rate in the sample')],
   findings='Net sales reconciled to $8,096,531 across 80,095 purchasing customers. Session conversion was 26.6%. Similar cart-abandonment rates across channels suggest testing the onsite journey before assuming that media allocation is the main cause.',
   decision='Prioritize an onsite checkout hypothesis and differentiated lifecycle treatments. Use net sales and repeat behavior to evaluate them; verify the result with a prospective test.',
   limits='TheLook is synthetic. Its $8.10M net sales is a dataset result, not revenue I generated. May 2024 is incomplete. Marketing spend is absent, so CAC and ROAS cannot be calculated. A return-propensity model achieved ROC-AUC about 0.50 and was not recommended for deployment.',
   chart_caption='Customer and cohort view from the synthetic-data Power BI report.',
   repo='https://github.com/kath-pahotu/the-look-ecommerce-data-analysis',
   source_note='Source: project analysis findings, architecture, source inventory and assumptions documentation.'),
 'rokt': dict(name='Rokt holdout experiment', domain='Experimentation', capability='Experimentation',
   data_slug='rokt-experiment', marketing_slug='rokt', duration='Approximately 2 weeks',
   provenance='Independent analysis of a supplied experiment dataset', tools=['Python','Two-proportion z-test','Assignment audit','Sensitivity analysis'],
   metric='+13.9%', metric_label='primary relative uplift; +5.5% in sensitivity', image='rokt-dashboard.png',
   data_title='Audit the assignment before trusting the uplift',
   marketing_title='Did the ads produce additional conversions?',
   data_intro='An ad-holdout analysis that makes the randomization-unit uncertainty and sensitivity results part of the answer.',
   marketing_intro='A positive conversion signal, evaluated against a suppressed-ad holdout and checked before using it to size a campaign rollout.',
   problem='Did ad exposure increase conversion, and how much does that conclusion depend on the unit used to count users?',
   methods=[('Data cleaning','Removed 36,893 exact duplicates, excluded an invalid cohort row and normalized device values, leaving 852,197 cleaned records.'),
     ('Experiment evaluation','Compared unique converted users with unique users within each group, using a two-proportion z-test and confidence intervals.'),
     ('Assignment-unit audit','Found 26,426 users appearing in both groups across months and 92 overlapping user-cohort pairs. Monthly reassignment is plausible, but the randomization unit is not explicitly documented.'),
     ('Sensitivity analysis','Re-estimated the comparison at user-cohort and session level. Used the difference to qualify the headline effect and define the evidence needed for rollout.')],
   results=[('2.23%','treatment conversion'),('1.95%','holdout conversion'),('+13.9%','primary relative uplift; p = 3.42e-09'),('+5.5%','user-cohort uplift; p = 0.016')],
   findings='The primary comparison suggests a positive effect, with a relative-uplift interval of +9.1% to +19.0%. The user-cohort sensitivity estimate is smaller. The direction is encouraging; the magnitude depends on how assignment and repeat users are handled.',
   decision='Confirm the randomization unit and reassignment policy before sizing rollout. Investigate the decline across monthly cohorts and use device differences to propose follow-up tests.',
   limits='This is analysis of a supplied dataset, not a campaign I ran for Rokt. Repeated users can create dependence across months. Conventional p-values do not resolve the assignment ambiguity. The estimated additional conversions are a counterfactual calculation, not verified realized impact.',
   chart_caption='Aggregate-only experiment dashboard. Primary and sensitivity results must be interpreted together.',
   repo='https://github.com/kath-pahotu/au_rokt', source_note='Source: executive summary and methodology, including the assignment-unit audit.'),
 'bank': dict(name='Bank campaign targeting', domain='Bank and fintech', capability='Campaign targeting',
   data_slug='bank-marketing', marketing_slug='campaign-targeting', duration='Approximately 2 weeks',
   provenance='Independent study of the public UCI Bank Marketing dataset', tools=['SQL','Python','scikit-learn','Propensity modeling'],
   metric='2.59×', metric_label='offline targeting lift in the top 20%', image='bank-targeting.png',
   data_title='Leakage-controlled propensity modeling for outreach',
   marketing_title='Reach likely responders within a limited call budget',
   data_intro='A pre-contact random forest evaluated with PR-AUC, ROC-AUC and targeting lift on an untouched test set.',
   marketing_intro='Turn a customer ranking into a practical reach-versus-efficiency decision for the next campaign pilot.',
   problem='If a team can contact only a fifth of its audience, which records should it prioritize and how many historical responders would that capture?',
   methods=[('Scoring-time contract','Used 45,211 historical contact records. Excluded call duration and current campaign count, plus current contact channel and timing, from the pre-contact candidate.'),
     ('Model selection','Compared logistic regression and random forest with five-fold stratified cross-validation within the training data. Chose average precision / PR-AUC for the imbalanced response outcome.'),
     ('Untouched test evaluation','Measured PR-AUC, ROC-AUC, lift and responder capture on the held-out test partition. Used permutation importance to interpret the ranking.'),
     ('Campaign capacity','Compared 10%, 20%, 30% and 50% outreach bands. Recommended a controlled pilot whose thresholds reflect actual call costs, staffing and customer value.')],
   results=[('0.738','test ROC-AUC'),('0.384','test PR-AUC'),('51.8%','responders captured in top 20%'),('30.3%','observed conversion in that band')],
   findings='The top 20% of ranked test records captured 51.8% of historical responders at 2.59× lift over the test baseline. This is a useful capacity scenario: a manager can see what is gained in response efficiency and lost in reach.',
   decision='Run a randomized prospective pilot against existing targeting. Track incremental subscriptions, contact cost, opt-outs and complaints; review feature suitability before operational use.',
   limits='The 2.59× lift is predictive performance on historical data, not causal campaign lift or achieved cost savings. The dataset lacks stable customer IDs and a full timestamp, so grouped and reliable out-of-time validation are unavailable. Scores rank records; they are not calibrated probabilities.',
   chart_caption='Historical responder capture and lift by contact capacity. The top-20% band is a pilot scenario.',
   repo='https://github.com/kath-pahotu/bank_marketing_campaign_analysis', source_note='Source: README model evaluation and capacity table; methodology and scoring-time contract.'),
 'zalopay': dict(name='ZaloPay promotion review', domain='Bank and fintech', capability='Promotion efficiency',
   data_slug='zalopay-promo-abuse', marketing_slug='promotion-review', duration='Approximately 1 month',
   provenance='Independent fintech case study; public outputs anonymized', tools=['T-SQL','Python','Power BI','Rule simulation'],
   metric='26.94%', metric_label='credited cost associated with 4.26% of scored users', image='zalopay-exec.png',
   data_title='An explainable review queue for promotion-abuse signals',
   marketing_title='Focus promotion review where budget exposure concentrates',
   data_intro='Six behavioral signals, independently reconciled SQL/Python calculations and a cost-aware manual review recommendation.',
   marketing_intro='Connect promotion-cost concentration with investigation capacity while preserving the distinction between unusual behavior and confirmed abuse.',
   problem='Which users deserve manual review, and what share of credited promotion cost is associated with a manageable review queue?',
   methods=[('SQL exploration and features','Examined campaign performance and built behavioral signals for immediate redemption, credited discount, referrals, shared devices, shared IPs and reciprocal transfers.'),
     ('Cost concentration','Compared the score-based population with its share of credited promotion cost, preserving the distinction between scored users and all campaign users.'),
     ('Python rule simulation','Simulated alternative rules and reconciled their outputs with SQL. Compared queue size and cost exposure rather than claiming unobserved fraud precision.'),
     ('Decision reporting','Built Power BI views for budget concentration, merchant exposure, review priority, rule trade-offs and overall-payment retention context.')],
   results=[('86,170','scored users'),('4.26%','score-based priority cohort'),('26.94%','credited cost associated with that cohort'),('1,994','users in the balanced candidate queue')],
   findings='The score-based cohort contains 3,671 users. Separately, the medium-balanced candidate flags 1,994 users (2.31% of scored users) and covers 23.89% of credited promotion cost. These are different definitions, so their percentages should not be combined.',
   decision='Start the balanced rule in shadow mode with manual review. Collect investigator outcomes to evaluate customer impact and precision before considering automated actions.',
   limits='There are no confirmed fraud labels. A flag is a review-priority signal, not proof of fraud; cost exposure is not recovered savings. Zero low-score impact is an internal consistency check, not a measured false-positive rate. Overall-payment retention is not campaign-attributed retention. This was not employment at ZaloPay.',
   chart_caption='Anonymized aggregate Power BI view of promotion cost and review prioritization.',
   repo='https://github.com/kath-pahotu/zalopay-promo-abuse-detection', source_note='Source: abuse-impact summary, candidate-rule simulation CSV and insights documentation.'),
 'mobility': dict(name='Mobility and delivery growth', domain='Ecommerce', capability='Acquisition and measurement',
   data_slug='mobility-delivery', marketing_slug='growth-and-retention', duration='Approximately 2 weeks',
   provenance='Independent business-analysis case using confidential company data', tools=['Excel','Growth segmentation','Cohort retention','Channel measurement'],
   metric='3', metric_label='connected growth decisions; confidential figures', image=None,
   data_title='Validate the growth story across partner and customer data',
   marketing_title='Connect channel spend to activation and repeat use',
   data_intro='Three analyses of a real mobility and delivery marketplace, with validation of aggregate definitions, alert logic and business proxies.',
   marketing_intro='An acquisition, retention and subsidy review that connects marketing investment with downstream customer behavior.',
   problem='How should a marketplace allocate subsidies and channel budgets when top-line growth, acquisition volume and durable customer value point in different directions?',
   methods=[('Partner growth and subsidies','Separated absolute GMV from discount intensity, compared partner segments and funding mix, and developed a four-quadrant investment framework. Used weighted forecasts as directional scenarios.'),
     ('Retention and user journeys','Decomposed first-month retention by acquisition source, region, service and customer segment. Distinguished app re-entry, early intent and checkout bottlenecks.'),
     ('Acquisition and channel quality','Investigated divergence between installs and activated users. Compared channel spend, acquisition, bookings, GMV, CAC and cost-to-income ratios, with CPC measurement where definitions support it.'),
     ('Data quality and measurement limits','Corrected national-versus-regional aggregation and false-positive decline alerts. Kept top-line spend ratios separate from profit-based ROAS and contribution measures.')],
   results=[('Partner investment','scale and subsidy intensity considered together'),('Retention priorities','re-entry and checkout diagnosed separately'),('Channel decisions','activation and downstream value added to volume'),('Public evidence','qualitative only; all source figures withheld')],
   findings='The work translated three business questions into partner investment priorities, retention hypotheses and controlled budget-change guardrails. Validation of totals and alert rules was part of the analysis, not a separate reporting afterthought.',
   decision='Test focused subsidy, funnel and channel changes with acquisition, value and efficiency guardrails. Use holdouts or suitable controlled designs to estimate incrementality; collect cohort contribution data before making payback claims.',
   limits='This is an independent case study, not employment at the company. Public material omits the company name, partner/channel identities and internal figures. Aggregate observational data supports diagnostic hypotheses, not causal uplift. Completed analysis used Excel. SQL/Python rebuilding, causal incrementality tests and cohort ROAS/payback are proposed next steps.',
   chart_caption='', repo=None, source_note='Source: privately reviewed growth, retention and marketing-measurement reports. Public summary intentionally contains no raw records or exact business figures.')
}

EDUCATION = [
 'Bachelor of Business Administration | University of Economics Ho Chi Minh City | 2018-2022',
 'TheHau Data Analytics Mentoring Program | Mar-Jul 2025',
 'IELTS Overall Band 7.5 | 2022'
]
SKILLS = {
 'data': [('Ecommerce','ELT, star schemas, funnel and cohort retention, net-sales reconciliation; DuckDB, SQL, Python and Power BI.'),
          ('Bank and fintech projects','Pre-contact propensity ML, PR-AUC/ROC-AUC, targeting lift, explainable risk signals and review-cost coverage.'),
          ('SaaS and measurement','GA4, BigQuery, Looker Studio, web/product funnels, experiment analysis, randomization audits and sensitivity checks.')],
 'marketing': [('Acquisition and targeting','Channel and lead-quality analysis, campaign planning, Google/Meta Ads, SEO, predictive targeting and lift.'),
               ('Growth and budget efficiency','Funnel and cohort retention, promotion cost, marketplace subsidies, CAC/CIR and measurement planning.'),
               ('Analytics and leadership','GA4, Looker Studio, SQL, Excel, Python and Power BI; KPI design, resource planning and team guidance.')]
}
CV_PROJECTS = {
 'data': {
  'thelook': ['Built a reproducible DuckDB SQL/Python ELT pipeline from 7 files and 2.42M events; rebuilt 680,862 sessions, modeled a star schema and delivered a seven-page Power BI report.',
              'Reconciled $8.10M net sales in synthetic data; analyzed 58.0% cart abandonment and 37.3% repeat-customer rate with explicit metric definitions and validation.'],
  'rokt': ['Audited 852,197 cleaned records and assignment overlap; estimated +13.9% primary relative uplift (p = 3.42e-09) and +5.5% in user-cohort sensitivity (p = 0.016).',
           'Used two-proportion tests and confidence intervals; recommended confirming the randomization unit before sizing rollout.'],
  'bank': ['Built a leakage-controlled pre-contact random forest on 45,211 records; achieved test ROC-AUC 0.738 and PR-AUC 0.384.',
           'Top 20% captured 51.8% of historical responders at 2.59x offline lift; recommended a randomized pilot before live use.'],
  'zalopay': ['Engineered six behavioral signals in T-SQL, reconciled Python simulations and built Power BI reporting; 4.26% of scored users accounted for 26.94% of credited promotion cost.',
              'Recommended a manual shadow-review queue. Unlabeled risk signals do not establish fraud or recovered savings.'],
  'mobility': ['Used Excel to analyze partner scale, subsidy intensity, first-month retention and channel efficiency on confidential company data.',
               'Corrected aggregate/region definitions and alert logic; proposed budget and funnel actions with measurement guardrails. Public results are qualitative.']},
 'marketing': {
  'mobility': ['Connected partner subsidy economics, first-month retention and channel spend with activation and downstream value using confidential company data in Excel.',
               'Diagnosed re-entry and checkout barriers; proposed controlled channel changes with acquisition and efficiency guardrails. Outcomes are recommendations; figures remain confidential.'],
  'bank': ['Ranked historical outreach records for a constrained campaign: the top 20% captured 51.8% of responders at 30.3% conversion and 2.59x offline lift.',
           'Defined a prospective pilot to test incremental response and contact economics; excluded information unavailable before outreach.'],
  'rokt': ['Evaluated an ad holdout: treatment conversion was 2.23% versus 1.95%, or +13.9% relative uplift. User-cohort sensitivity estimated +5.5% (p = 0.016).',
           'Audited assignment overlap and set rollout conditions rather than treating the headline estimate as guaranteed campaign impact.'],
  'zalopay': ['Linked 4.26% of scored users to 26.94% of credited promotion cost; compared investigation workload with cost coverage using SQL, Python and Power BI.',
              'Recommended shadow-mode review and investigator feedback. No confirmed fraud, recovered savings or automatic blocking claimed.'],
  'thelook': ['Connected acquisition, funnel, cohort retention and RFM segmentation across 2.42M synthetic events in SQL, Python and Power BI.',
              'Diagnosed 58.0% cart abandonment and 37.3% repeat-customer rate; framed checkout and lifecycle tests. No marketing-cost data was available for ROAS.']}
}
